/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.parandroid.sms;

public final class R {
    public static final class anim {
        public static final int cycle_7=0x7f040000;
        public static final int fade=0x7f040001;
        public static final int hyperspace_in=0x7f040002;
        public static final int hyperspace_out=0x7f040003;
        public static final int layout_animation_row_left_slide=0x7f040004;
        public static final int layout_animation_row_right_slide=0x7f040005;
        public static final int layout_animation_table=0x7f040006;
        public static final int layout_bottom_to_top_slide=0x7f040007;
        public static final int layout_grid_fade=0x7f040008;
        public static final int layout_grid_inverse_fade=0x7f040009;
        public static final int layout_random_fade=0x7f04000a;
        public static final int layout_wave_scale=0x7f04000b;
        public static final int push_left_in=0x7f04000c;
        public static final int push_left_out=0x7f04000d;
        public static final int push_up_in=0x7f04000e;
        public static final int push_up_out=0x7f04000f;
        public static final int shake=0x7f040010;
        public static final int slide_left=0x7f040011;
        public static final int slide_right=0x7f040012;
        public static final int slide_top_to_bottom=0x7f040013;
        public static final int wave_scale=0x7f040014;
    }
    public static final class array {
        /**  NOTE: if you change anything about this array, you must make the corresponding change
         to the array DEFAULT_SMILEY_RES_IDS in MessageListItem.java and to default_smiley_texts
         above. 
 16: o_O 
         */
        public static final int default_smiley_names=0x7f060001;
        /**  NOTE: if you change anything about this array, you must make the corresponding change
         to the array DEFAULT_SMILEY_RES_IDS in MessageListItem.java and to default_smiley_names
         below. 
 16: Confused 
         */
        public static final int default_smiley_texts=0x7f060000;
        /**  Options for slide duration in duration selection dialog box 
         */
        public static final int select_dialog_items=0x7f060002;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int read_bgcolor=0x7f070002;
        /**  Chat "sent time" text background 
         */
        public static final int timestamp_color=0x7f070000;
        /**  the background color used for unread conversation 
         */
        public static final int unread_bgcolor=0x7f070001;
    }
    public static final class drawable {
        public static final int attachment_editor_bg=0x7f020000;
        public static final int bottombar_landscape_565=0x7f020001;
        public static final int chat_history_selector=0x7f020002;
        /**  Activity background color 
         */
        public static final int class_zero_background=0x7f02004f;
        public static final int contact_picture_bg=0x7f020003;
        public static final int conversation_item_background_read=0x7f020004;
        public static final int conversation_item_background_unread=0x7f020005;
        public static final int fasttrack_badge_middle=0x7f020006;
        public static final int fasttrack_badge_middle_normal=0x7f020007;
        public static final int fasttrack_badge_middle_pressed=0x7f020008;
        public static final int ic_accepted=0x7f020009;
        public static final int ic_attachment_universal_small=0x7f02000a;
        public static final int ic_change_password=0x7f02000b;
        public static final int ic_contact_picture=0x7f02000c;
        public static final int ic_dialog_attach=0x7f02000d;
        public static final int ic_dialog_email_pending=0x7f02000e;
        public static final int ic_email_pending=0x7f02000f;
        public static final int ic_gallery_video_overlay=0x7f020010;
        public static final int ic_generate_keypair=0x7f020011;
        public static final int ic_groupchat=0x7f020012;
        public static final int ic_launcher_camera=0x7f020013;
        public static final int ic_launcher_camera_record=0x7f020014;
        public static final int ic_launcher_gallery=0x7f020015;
        public static final int ic_launcher_musicplayer_2=0x7f020016;
        public static final int ic_launcher_record_audio=0x7f020017;
        public static final int ic_launcher_slideshow_add_sms=0x7f020018;
        public static final int ic_launcher_slideshow_default_sms=0x7f020019;
        public static final int ic_launcher_smsmms=0x7f02001a;
        public static final int ic_launcher_video_player=0x7f02001b;
        public static final int ic_list_alert_sms_failed=0x7f02001c;
        public static final int ic_lock_message_sms=0x7f02001d;
        public static final int ic_manage_public_keys=0x7f02001e;
        public static final int ic_maps_back=0x7f02001f;
        public static final int ic_maps_next=0x7f020020;
        public static final int ic_menu_add_slide=0x7f020021;
        public static final int ic_menu_add_sound=0x7f020022;
        public static final int ic_menu_attachment=0x7f020023;
        public static final int ic_menu_contact=0x7f020024;
        public static final int ic_menu_delete_played=0x7f020025;
        public static final int ic_menu_duration=0x7f020026;
        public static final int ic_menu_move_down=0x7f020027;
        public static final int ic_menu_move_up=0x7f020028;
        public static final int ic_menu_movie=0x7f020029;
        public static final int ic_menu_picture=0x7f02002a;
        public static final int ic_menu_remove_picture=0x7f02002b;
        public static final int ic_menu_remove_sound=0x7f02002c;
        public static final int ic_menu_remove_text=0x7f02002d;
        public static final int ic_menu_remove_video=0x7f02002e;
        public static final int ic_missing_thumbnail_picture=0x7f02002f;
        public static final int ic_missing_thumbnail_video=0x7f020030;
        public static final int ic_mms_drm_protected=0x7f020031;
        public static final int ic_mms_duration=0x7f020032;
        public static final int ic_mms_layout=0x7f020033;
        public static final int ic_mms_message_details=0x7f020034;
        public static final int ic_mms_music=0x7f020035;
        public static final int ic_mms_text_bottom=0x7f020036;
        public static final int ic_mms_text_top=0x7f020037;
        public static final int ic_pending=0x7f020038;
        public static final int ic_send_public_key=0x7f020039;
        public static final int ic_sms_mms_delivered=0x7f02003a;
        public static final int ic_sms_mms_not_delivered=0x7f02003b;
        public static final int ic_sms_mms_pending=0x7f02003c;
        public static final int ic_sms_unread_msg_indicator=0x7f02003d;
        /**  Widget background 
         */
        public static final int light_blue_background=0x7f020050;
        public static final int listitem_background=0x7f02003e;
        public static final int listitem_background_lightblue=0x7f02003f;
        public static final int mms_play_btn=0x7f020040;
        public static final int movie=0x7f020041;
        public static final int parandroid_btn_check=0x7f020042;
        public static final int parandroid_encrypt_msg=0x7f020043;
        public static final int parandroid_plain_msg=0x7f020044;
        public static final int public_key_manager_tab=0x7f020045;
        public static final int stat_notify_encrypted_msg=0x7f020046;
        public static final int stat_notify_encrypted_msg_background=0x7f020047;
        public static final int stat_notify_mms=0x7f020048;
        public static final int stat_notify_public_key_recieved=0x7f020049;
        public static final int stat_notify_sms=0x7f02004a;
        public static final int stat_notify_sms_failed=0x7f02004b;
        public static final int stat_sys_no_sim=0x7f02004c;
        /**  text color 
         */
        public static final int text_color=0x7f020052;
        public static final int text_color_black=0x7f020054;
        public static final int text_color_offwhite=0x7f020055;
        public static final int text_color_red=0x7f020053;
        public static final int textfield_im_user_pressed_pad=0x7f02004d;
        public static final int textfield_im_user_selected_pad=0x7f02004e;
        public static final int white_background=0x7f020051;
    }
    public static final class id {
        public static final int addrecipientbutton=0x7f0b0060;
        public static final int album_name=0x7f0b0003;
        public static final int artist_name=0x7f0b0004;
        public static final int attachment=0x7f0b0029;
        public static final int attachment_editor=0x7f0b0012;
        public static final int attachment_icon=0x7f0b0073;
        public static final int attachment_name=0x7f0b0072;
        public static final int audio=0x7f0b0032;
        public static final int audio_attachment_view_landscape=0x7f0b0001;
        public static final int audio_attachment_view_landscape_stub=0x7f0b0019;
        public static final int audio_attachment_view_portrait=0x7f0b0009;
        public static final int audio_attachment_view_portrait_stub=0x7f0b0015;
        public static final int audio_error_msg=0x7f0b0005;
        public static final int audio_icon=0x7f0b0058;
        public static final int audio_name=0x7f0b0002;
        public static final int avatar=0x7f0b0024;
        public static final int body_text_view=0x7f0b005e;
        public static final int bottom_panel=0x7f0b001b;
        public static final int btn_download_msg=0x7f0b0051;
        public static final int btn_no=0x7f0b0023;
        public static final int btn_yes=0x7f0b0022;
        public static final int buttonPanel=0x7f0b0021;
        public static final int button_next=0x7f0b0043;
        public static final int button_previous=0x7f0b0042;
        public static final int button_send_public_key=0x7f0b0040;
        public static final int cancelbutton=0x7f0b000c;
        public static final int contact_header=0x7f0b000d;
        public static final int contact_name=0x7f0b0078;
        public static final int contact_status=0x7f0b0079;
        public static final int controler=0x7f0b0033;
        public static final int date=0x7f0b0027;
        public static final int delete_locked=0x7f0b002b;
        public static final int done=0x7f0b003d;
        public static final int done_button=0x7f0b003a;
        public static final int duration_text=0x7f0b0074;
        public static final int edit_slideshow_button=0x7f0b006c;
        public static final int editor_with_counter=0x7f0b001c;
        public static final int embedded_text_editor=0x7f0b001d;
        public static final int empty_message=0x7f0b0067;
        public static final int error=0x7f0b0028;
        public static final int from=0x7f0b0026;
        public static final int generate_new_keypair=0x7f0b003f;
        public static final int help_flipper=0x7f0b003e;
        public static final int history=0x7f0b0011;
        public static final int icon=0x7f0b002c;
        public static final int image=0x7f0b0031;
        public static final int image_attachment_view_landscape=0x7f0b0045;
        public static final int image_attachment_view_landscape_stub=0x7f0b0017;
        public static final int image_attachment_view_portrait=0x7f0b0049;
        public static final int image_attachment_view_portrait_stub=0x7f0b0013;
        public static final int image_content=0x7f0b0046;
        public static final int image_preview=0x7f0b006f;
        public static final int image_view=0x7f0b0054;
        public static final int label=0x7f0b003b;
        public static final int label_downloading=0x7f0b0052;
        public static final int message=0x7f0b002a;
        public static final int messages=0x7f0b0066;
        public static final int mms_download_controls=0x7f0b0050;
        public static final int mms_downloading_view_stub=0x7f0b004f;
        public static final int mms_layout_view_parent=0x7f0b004b;
        public static final int mms_layout_view_stub=0x7f0b004c;
        public static final int mms_view=0x7f0b0053;
        public static final int msg_list_item=0x7f0b004a;
        public static final int name=0x7f0b0059;
        public static final int name_and_label=0x7f0b005a;
        public static final int next_slide_button=0x7f0b0035;
        public static final int notify_no_recipient=0x7f0b0062;
        public static final int notify_tap_to_remove=0x7f0b0063;
        public static final int number=0x7f0b005b;
        public static final int number_picker=0x7f0b0056;
        public static final int password=0x7f0b000a;
        public static final int password_confirm=0x7f0b0065;
        public static final int play_audio_button=0x7f0b0006;
        public static final int play_slideshow_button=0x7f0b0055;
        public static final int playing_audio=0x7f0b0057;
        public static final int pre_slide_button=0x7f0b0034;
        public static final int presence=0x7f0b0025;
        public static final int presence_icon=0x7f0b007a;
        public static final int preview_button=0x7f0b0036;
        public static final int progress_bar=0x7f0b0041;
        public static final int public_keys=0x7f0b0000;
        public static final int recipient=0x7f0b002e;
        public static final int recipients=0x7f0b0064;
        public static final int recipients_editor=0x7f0b005c;
        public static final int recipients_editor_stub=0x7f0b000f;
        public static final int recipients_subject_linear=0x7f0b000e;
        public static final int remove_audio_button=0x7f0b0008;
        public static final int remove_image_button=0x7f0b0048;
        public static final int remove_slide_button=0x7f0b0038;
        public static final int remove_video_button=0x7f0b007f;
        public static final int replace_audio_button=0x7f0b0007;
        public static final int replace_image_button=0x7f0b0037;
        public static final int replace_video_button=0x7f0b007e;
        public static final int right_status_indicator=0x7f0b004e;
        public static final int send_button=0x7f0b0020;
        public static final int send_slideshow_button=0x7f0b006d;
        public static final int sendbutton=0x7f0b0061;
        public static final int slide_editor_view=0x7f0b0030;
        public static final int slide_number_text=0x7f0b0070;
        public static final int slide_view=0x7f0b0068;
        public static final int slideshow_attachment_view_landscape=0x7f0b0069;
        public static final int slideshow_attachment_view_landscape_stub=0x7f0b001a;
        public static final int slideshow_attachment_view_portrait=0x7f0b006e;
        public static final int slideshow_attachment_view_portrait_stub=0x7f0b0016;
        public static final int slideshow_image=0x7f0b006a;
        public static final int slideshow_text=0x7f0b006b;
        public static final int smiley_icon=0x7f0b0075;
        public static final int smiley_name=0x7f0b0076;
        public static final int smiley_text=0x7f0b0077;
        public static final int status=0x7f0b002f;
        public static final int subject=0x7f0b0010;
        public static final int submitbutton=0x7f0b000b;
        public static final int subtitle=0x7f0b005f;
        public static final int text=0x7f0b003c;
        public static final int text1=0x7f0b0044;
        public static final int text_counter=0x7f0b001f;
        public static final int text_message=0x7f0b0039;
        public static final int text_preview=0x7f0b0071;
        public static final int text_view=0x7f0b004d;
        public static final int title=0x7f0b002d;
        public static final int title_text_view=0x7f0b005d;
        public static final int try_to_encrypt=0x7f0b001e;
        public static final int video_attachment_view_landscape=0x7f0b007b;
        public static final int video_attachment_view_landscape_stub=0x7f0b0018;
        public static final int video_attachment_view_portrait=0x7f0b0080;
        public static final int video_attachment_view_portrait_stub=0x7f0b0014;
        public static final int video_thumbnail=0x7f0b007c;
        public static final int view_image_button=0x7f0b0047;
        public static final int view_video_button=0x7f0b007d;
    }
    public static final class layout {
        public static final int about_activity=0x7f030000;
        public static final int accepted_keys_activity=0x7f030001;
        public static final int audio_attachment_view_landscape=0x7f030002;
        public static final int audio_attachment_view_portrait=0x7f030003;
        public static final int authenticate_activity=0x7f030004;
        public static final int compose_message_activity=0x7f030005;
        public static final int confirm_rate_limit_activity=0x7f030006;
        public static final int conversation_header=0x7f030007;
        public static final int conversation_list_screen=0x7f030008;
        public static final int delete_thread_dialog_view=0x7f030009;
        public static final int delivery_report_activity=0x7f03000a;
        public static final int delivery_report_header=0x7f03000b;
        public static final int delivery_report_list_item=0x7f03000c;
        public static final int edit_slide_activity=0x7f03000d;
        public static final int edit_slide_duration=0x7f03000e;
        public static final int edit_slide_text=0x7f03000f;
        public static final int help_activity=0x7f030010;
        public static final int icon_list_item=0x7f030011;
        public static final int image_attachment_view_landscape=0x7f030012;
        public static final int image_attachment_view_portrait=0x7f030013;
        public static final int message_list_item=0x7f030014;
        public static final int mms_downloading_view=0x7f030015;
        public static final int mms_layout_view=0x7f030016;
        public static final int number_picker=0x7f030017;
        public static final int playing_audio_info=0x7f030018;
        public static final int public_key_manager_activity=0x7f030019;
        public static final int public_key_receiver_activity=0x7f03001a;
        public static final int public_key_recipient_item=0x7f03001b;
        public static final int recipient_filter_item=0x7f03001c;
        public static final int recipients_editor=0x7f03001d;
        public static final int retry_sending_dialog=0x7f03001e;
        public static final int search_activity=0x7f03001f;
        public static final int search_item=0x7f030020;
        public static final int send_public_key_activity=0x7f030021;
        public static final int set_password_activity=0x7f030022;
        public static final int sim_list=0x7f030023;
        public static final int slideshow=0x7f030024;
        public static final int slideshow_attachment_view_landscape=0x7f030025;
        public static final int slideshow_attachment_view_portrait=0x7f030026;
        public static final int slideshow_edit_item=0x7f030027;
        public static final int smiley_menu_item=0x7f030028;
        public static final int titlebar=0x7f030029;
        public static final int video_attachment_view_landscape=0x7f03002a;
        public static final int video_attachment_view_portrait=0x7f03002b;
    }
    public static final class plurals {
        /**   Search results title 
         */
        public static final int search_results_title=0x7f090001;
        /**  Duration of the slide, shown in the list in the slideshow editor 
         */
        public static final int slide_duration=0x7f090000;
    }
    public static final class string {
        public static final int about_string=0x7f08010f;
        public static final int about_title=0x7f08011d;
        public static final int accept_public_key=0x7f08014a;
        /**  Menu item in conversation screen for attaching something to the message being composed 
         */
        public static final int add_attachment=0x7f080039;
        /**  Title of the add-attachment activity. 
         */
        public static final int add_attachment_activity=0x7f0800f9;
        /**  Menu item in slide edit screen for adding music to the slide being edited 
         */
        public static final int add_music=0x7f080032;
        /**  Menu item in slide edit screen for adding a picture to the slide being edited 
         */
        public static final int add_picture=0x7f080030;
        public static final int add_recipient=0x7f08013f;
        /**  Menu item in slideshow edit screen for adding a new slide to the slideshow 
         */
        public static final int add_slide=0x7f08002b;
        /**  Text displayed below "Add slide" item in slideshow edit screen 
         */
        public static final int add_slide_hint=0x7f08002c;
        /**  Menu item in conversation screen for adding a subject to the message being composed 
         */
        public static final int add_subject=0x7f08003a;
        /**  Menu item in slide edit screen for adding a video to the slide being edited 
         */
        public static final int add_video=0x7f080034;
        /**  Menu item in conversation screen for returning to the conversation list 
         */
        public static final int all_threads=0x7f080040;
        /**  Name to use when we have an unspecified sender 
         */
        public static final int anonymous_recipient=0x7f08000f;
        /**  Parandroid SMS 
         */
        public static final int app_label=0x7f08010e;
        /**  Dialog message text asking the user if he wants to resize the picture being attached 
         */
        public static final int ask_for_automatically_resize=0x7f080044;
        /**  Attachment Type Selector Adapter. This string is an option in the "Attach" dialog, "Add music" dialog 
         */
        public static final int attach_image=0x7f0800c9;
        /**  Attachment Type Selector Adapter. This string is an option in the "Attach" dialog, "Add music" dialog 
         */
        public static final int attach_record_sound=0x7f0800ce;
        /**  Attachment Type Selector Adapter. This string is an option in the "Attach" dialog, "Add music" dialog 
         */
        public static final int attach_record_video=0x7f0800cc;
        /**  Attachment Type Selector Adapter. This string is an option in the "Attach" dialog, "Add music" dialog 
         */
        public static final int attach_slideshow=0x7f0800cf;
        /**  Attachment Type Selector Adapter. This string is an option in the "Attach" dialog, "Add music" dialog 
         */
        public static final int attach_sound=0x7f0800cd;
        /**  Attachment Type Selector Adapter. This string is an option in the "Attach" dialog, "Add music" dialog 
         */
        public static final int attach_take_photo=0x7f0800ca;
        /**  Attachment Type Selector Adapter. This string is an option in the "Attach" dialog, "Add music" dialog 
         */
        public static final int attach_video=0x7f0800cb;
        /**  Label in "Message details" dialog 
         */
        public static final int bcc_label=0x7f0800a8;
        /**  Appearance of message sender in multi-recipient messages, e.g. "me to Megan" 
 unknown quoting pattern: original -1, translation 1 
         */
        public static final int broadcast_from_to=0x7f08000e;
        /**  Brief message that appears when user tries to add picture to a slide which already has a video. 
         */
        public static final int cannot_add_picture_and_video=0x7f080059;
        /**  Brief message that appears when the maximum number of slides has been reached 
         */
        public static final int cannot_add_slide_anymore=0x7f080058;
        /**  Error message displayed when the user attempts to forward a message with DRM-locked contents 
         */
        public static final int cannot_forward_drm_obj=0x7f080055;
        /**  When the user tries to view message details and some error occurs while
         retrieving those details, this message will be shown. 
         */
        public static final int cannot_get_details=0x7f0800a0;
        public static final int cannot_load_message=0x7f08005b;
        /**  Error message indicating that an audio attachment cannot be played 
         */
        public static final int cannot_play_audio=0x7f080060;
        /**  Brief message that appears when the message cannot be saved 
         */
        public static final int cannot_save_message=0x7f08005a;
        /**  Dialog box title indicating the message cannot be sent because there are no valid recipients 
         */
        public static final int cannot_send_message=0x7f080053;
        /**  Dialog message text indicating the message cannot be sent because there are no valid recipients 
         */
        public static final int cannot_send_message_reason=0x7f080054;
        /**  Title of the slide duration editor activity. 
         */
        public static final int change_duration_activity=0x7f0800fb;
        /**  Title of the class-0 message activity. 
         */
        public static final int class_0_message_activity=0x7f080101;
        public static final int close_on_sleep=0x7f080159;
        public static final int close_on_sleep_title=0x7f08015a;
        /**  Title bar displayed in compose message activity before a recipient has been selected 
         */
        public static final int compose_title=0x7f080036;
        /**  Toast message while an image is being resized 
         */
        public static final int compressing=0x7f080045;
        /**  Dialog title for the Read Report dialog. 
         */
        public static final int confirm=0x7f0800e0;
        /**  Delete the selected message on the SIM dialog message 
         */
        public static final int confirm_delete_SIM_message=0x7f08009d;
        /**  Delete all the messages on the SIM dialog message 
         */
        public static final int confirm_delete_all_SIM_messages=0x7f08009c;
        /**  Delete all threads confirmation dialog message 
         */
        public static final int confirm_delete_all_conversations=0x7f080098;
        /**  Delete entire thread confirmation dialog message 
         */
        public static final int confirm_delete_all_messages=0x7f08009b;
        /**  Delete entire thread confirmation dialog message 
         */
        public static final int confirm_delete_conversation=0x7f080097;
        /**  Delete message confirmation dialog message for a locked message 
         */
        public static final int confirm_delete_locked_message=0x7f08009a;
        /**  Delete message confirmation dialog message 
         */
        public static final int confirm_delete_message=0x7f080099;
        /**  Delete confirmation dialog title for locked messages 
         */
        public static final int confirm_dialog_locked_title=0x7f080096;
        /**  Confirm Delete 
 Delete confirmation dialog title 
         */
        public static final int confirm_dialog_title=0x7f080095;
        public static final int confirm_password=0x7f080126;
        /**  This is the confirm rate limit alert dialog text. 
         */
        public static final int confirm_rate_limit=0x7f0800e8;
        public static final int confirm_send_msg=0x7f080149;
        public static final int contact_name=0x7f080122;
        /**  Brief message that appears when converting a message from SMS to MMS. 
         */
        public static final int converting_to_picture_message=0x7f080056;
        /**  Brief message that appears when converting a message from MMS to SMS. 
         */
        public static final int converting_to_text_message=0x7f080057;
        /**  Individual message context menu item 
         */
        public static final int copy_message_text=0x7f080025;
        /**  Menu title to copy an attachment to the SD card 
         */
        public static final int copy_to_sdcard=0x7f0800ee;
        /**  Toast message on failed copy to SD card 
         */
        public static final int copy_to_sdcard_fail=0x7f0800f0;
        /**  Toast message on successful copy to SD card 
         */
        public static final int copy_to_sdcard_success=0x7f0800ef;
        public static final int corrupted_message=0x7f080143;
        /**  Summary text under "New Message" command; displays in conversation list 
         */
        public static final int create_new_message=0x7f080001;
        public static final int decline_public_key=0x7f08014b;
        public static final int decline_public_key_dialog=0x7f08014c;
        /**  Delete button title 
         */
        public static final int delete=0x7f08009f;
        /**  Context menu item on an individual message for deleting only that message 
         */
        public static final int delete_message=0x7f080016;
        public static final int delete_public_key=0x7f080147;
        public static final int delete_public_key_dialog=0x7f080148;
        /**  Menu item for deleting the entire conversation currently being viewed 
         */
        public static final int delete_thread=0x7f08001d;
        /**  Delete unlocked checkbox title 
         */
        public static final int delete_unlocked=0x7f08009e;
        /**  Delivery Header View 
 Title of "Report" window 
         */
        public static final int delivery_header_title=0x7f0800bf;
        /**  Title of the delivery report activity. 
         */
        public static final int delivery_report_activity=0x7f0800f7;
        /**  Delivery Report Toast dialog content 
         */
        public static final int delivery_toast_body=0x7f0800d2;
        /**  Menu item in conversation screen for discarding the message currently being composed 
         */
        public static final int discard=0x7f08003b;
        /**  Dialog box title that appears when a draft message will not be saved due to invalid recipients 
         */
        public static final int discard_message=0x7f08004e;
        /**  Dialog message text explaining that a draft message will not be saved due to invalid recipients 
         */
        public static final int discard_message_reason=0x7f08004f;
        /**  Menu item in slideshow edit screen for discarding the entire slideshow 
         */
        public static final int discard_slideshow=0x7f08002d;
        /**  While downloading a message, if that message has expired, display this message. 
         */
        public static final int dl_expired_notification=0x7f0800e6;
        /**  When an error occurs downloading a new message, display this message.
         An example: Download of message Wanna get pizza from dorkman was unsuccessful. 
         */
        public static final int dl_failure_notification=0x7f0800e5;
        /**  Button text on edit slide screen indicating the user wants to finish editing that slide 
         */
        public static final int done=0x7f080027;
        /**  Text of a button appearing for MMS messages that have not yet been downloaded, causing the message
         to be downloaded (imperative verb) 
         */
        public static final int download=0x7f08001f;
        /**  Dialog box message when there's a problem retrieving messages. 
         */
        public static final int download_later=0x7f0800ec;
        /**  Message displayed in place of the "download message" button once it has been pressed,
         indicating that the download is in progress 
         */
        public static final int downloading=0x7f080020;
        /**  Text to display when the actual text is inaccessible due to DRM protection 
         */
        public static final int drm_protected_text=0x7f080023;
        /**  Toast when the user enters a non-numeric value for the duration of a slide 
         */
        public static final int duration_not_a_number=0x7f08006a;
        /**  String for slide duration in seconds 
         */
        public static final int duration_sec=0x7f080064;
        /**  Dialog box title for duration selector 
         */
        public static final int duration_selector_title=0x7f080065;
        /**  Toast when the user enters a zero value for the duration of a slide 
         */
        public static final int duration_zero=0x7f08006b;
        /**  Button text used for editing a slideshow (imperative verb) 
         */
        public static final int edit=0x7f080074;
        /**  Title of the slide editor activity. 
         */
        public static final int edit_slide_activity=0x7f0800fe;
        /**  Title of the slideshow editor activity. 
         */
        public static final int edit_slideshow_activity=0x7f0800fd;
        /**  Title of the slide text editor activity. 
         */
        public static final int edit_text_activity=0x7f0800fc;
        public static final int enter_password=0x7f080125;
        /**  Message indicating that the message size limit has been reached 
         */
        public static final int exceed_message_size_limitation=0x7f080048;
        /**  Time and date a message is due to expire 
         */
        public static final int expire_on=0x7f080018;
        public static final int failed_changing_password=0x7f08014e;
        public static final int failed_opening_public_key=0x7f08012e;
        /**  Error message indicating that the item trying to be attached could not be added 
         */
        public static final int failed_to_add_media=0x7f08004a;
        /**  Error message indicating that the picture being attached and resized could not be resized 
         */
        public static final int failed_to_resize_image=0x7f08004b;
        public static final int forget_on_sleep=0x7f080157;
        public static final int forget_on_sleep_title=0x7f080158;
        /**  String prepended to forwarded messages to indicate they were forwarded 
         */
        public static final int forward_prefix=0x7f08004d;
        /**  Label in "Message details" dialog showing who sent the message. 
         */
        public static final int from_label=0x7f0800a6;
        public static final int generate_keypair_title=0x7f08011f;
        public static final int generate_new_keypair_dialog=0x7f08011e;
        public static final int generated_keypair_failure=0x7f080121;
        public static final int generating_keypair=0x7f080120;
        /**  Tag appearing on conversations in the conversation list that contain a draft message 
         */
        public static final int has_draft=0x7f08000d;
        /**  Dialog box title indicating which recipients are invalid when the user tries to send a message with invalid recipients 
         */
        public static final int has_invalid_recipient=0x7f080050;
        public static final int help_exchange_text=0x7f080166;
        public static final int help_exchange_title=0x7f080165;
        public static final int help_generate_text=0x7f08016a;
        public static final int help_generate_title=0x7f080169;
        public static final int help_intro_text=0x7f080160;
        public static final int help_intro_title=0x7f08015f;
        public static final int help_keypair_text=0x7f080162;
        public static final int help_keypair_title=0x7f080161;
        public static final int help_more_1_text=0x7f08016c;
        public static final int help_more_2_text=0x7f08016d;
        public static final int help_more_title=0x7f08016b;
        public static final int help_password_text=0x7f080164;
        public static final int help_password_title=0x7f080163;
        public static final int help_send_text=0x7f080168;
        public static final int help_send_title=0x7f080167;
        public static final int help_title=0x7f08015e;
        /**  Sender to be used if the sender address has been hidden 
         */
        public static final int hidden_sender_address=0x7f08006f;
        /**  Dialog title for warning the user that the picture they are trying to attach is too large 
         */
        public static final int image_too_large=0x7f080043;
        public static final int import_public_key=0x7f080134;
        public static final int import_public_key_dialog=0x7f080135;
        public static final int import_public_key_dialog_overwrite=0x7f080137;
        public static final int import_public_key_failure=0x7f080139;
        public static final int import_public_key_overwrite=0x7f080136;
        public static final int import_public_key_success=0x7f080138;
        /**  Formatting for subject displayed inline, prepended to MMS message text 
         */
        public static final int inline_subject=0x7f080022;
        /**  Error message to display when DRM rights are insufficient to access some data 
         */
        public static final int insufficient_drm_rights=0x7f080024;
        /**  While sending a message, if it has invalid recipient, display this message. 
         */
        public static final int invalid_destination=0x7f080051;
        /**  Dialog message text when the user tries to send a message with invalid recipients 
         */
        public static final int invalid_recipient_message=0x7f080052;
        /**  Abbreviation for "kilobyte" 
         */
        public static final int kilobyte=0x7f080019;
        /**  Slide layout option for layout at the bottom 
         */
        public static final int layout_bottom=0x7f080068;
        /**  Dialog box title for slide layout selector 
         */
        public static final int layout_selector_title=0x7f080066;
        /**  Slide layout option for layout at the top 
         */
        public static final int layout_top=0x7f080067;
        /**  Brief message that appears when an attempt is made to delete a locked message 
         */
        public static final int locked_message_cannot_be_deleted=0x7f08005d;
        public static final int long_press_for_options=0x7f08014d;
        public static final int menu_about=0x7f08011a;
        public static final int menu_add_address_to_contacts=0x7f080006;
        /**  Context menu item on a message recipient for adding them to the user's
         contacts (used if the recipient is not already in the address book) 
         */
        public static final int menu_add_to_contacts=0x7f08006e;
        /**  Menu item to call the recipient of the conversation on the phone (imperative verb) 
         */
        public static final int menu_call=0x7f080007;
        /**  Context menu item on an individual message for dialing the sender's phone number 
         */
        public static final int menu_call_back=0x7f080002;
        public static final int menu_change_password=0x7f080119;
        /**  Menu item for starting a new conversation 
         */
        public static final int menu_compose_new=0x7f080004;
        /**  Context menu item on an individual conversation for deleting that conversation 
         */
        public static final int menu_delete=0x7f080009;
        /**  Menu item for deleting all conversations 
         */
        public static final int menu_delete_all=0x7f080008;
        /**  Menu title for deleting undelivered messages or messages on
        the SIM card. 
         */
        public static final int menu_delete_messages=0x7f0800b6;
        /**  Menu title for editing a message 
         */
        public static final int menu_edit=0x7f0800b3;
        /**  Context menu item on an individual message for forwarding it to another recipient 
         */
        public static final int menu_forward=0x7f08001e;
        public static final int menu_generate_keypair=0x7f080116;
        public static final int menu_generate_new_keypair=0x7f080117;
        public static final int menu_help=0x7f08011b;
        /**  Menu item 
         */
        public static final int menu_insert_smiley=0x7f0800f4;
        /**  Menu title for locking a message 
         */
        public static final int menu_lock=0x7f0800b8;
        public static final int menu_manage_public_keys=0x7f080118;
        /**  Menu item for accessing application settings 
         */
        public static final int menu_preferences=0x7f080005;
        /**  Menu title the user can use for trying to resend a message. 
         */
        public static final int menu_retry_sending=0x7f0800b4;
        /**  Menu title the user can use for trying to resend all the messages. 
         */
        public static final int menu_retry_sending_all=0x7f0800b5;
        /**  Context menu item on an individual message for emailing the sender 
         */
        public static final int menu_send_email=0x7f080003;
        public static final int menu_send_public_key=0x7f080115;
        /**  This string is no longer used. It used to be the menu item for viewing all messages that
         were unable to be delivered, i.e. send failed 
         */
        public static final int menu_undelivered_messages=0x7f08000a;
        /**  Menu title for unlocking a message 
         */
        public static final int menu_unlock=0x7f0800b9;
        /**  Context menu item on an individual conversation for viewing that conversation 
         */
        public static final int menu_view=0x7f08000b;
        /**  Context menu item on a message recipient for viewing their contact info 
         */
        public static final int menu_view_contact=0x7f08006d;
        /**  Label in "Message details" dialog 
         */
        public static final int message_class_label=0x7f0800b2;
        /**  Title of "Message details" dialog 
         */
        public static final int message_details_title=0x7f0800a1;
        /**  Message Failed Notification 
 Dialog box title when receiving a message failed. 
         */
        public static final int message_download_failed_title=0x7f0800e9;
        /**  Dialog box message text when failure occurs sending a message. 
         */
        public static final int message_failed_body=0x7f0800eb;
        /**  Header for context menu on an individual message 
         */
        public static final int message_options=0x7f080026;
        /**  This is the text of a toast message briefly displayed when a problem occurs
         while sending. 
         */
        public static final int message_queued=0x7f0800e2;
        /**  Brief message that appears when a message has automatically been saved as a draft 
         */
        public static final int message_saved_as_draft=0x7f08005c;
        /**  Dialog box title when sending a message failed. 
         */
        public static final int message_send_failed_title=0x7f0800ea;
        /**  Dialog text for the Read Report dialog. 
         */
        public static final int message_send_read_report=0x7f0800e1;
        /**  Label in "Message details" dialog 
         */
        public static final int message_size_label=0x7f0800ad;
        /**  Message indicating that the message is too big and there is no space to attach a video 
         */
        public static final int message_too_big_for_video=0x7f080049;
        /**  Label in "Message details" dialog 
         */
        public static final int message_type_label=0x7f0800a2;
        /**  Name of the local user when displaying sender of an outgoing message (personal pronoun) 
         */
        public static final int messagelist_sender_self=0x7f080011;
        /**  Menu item in slideshow edit screen for moving the selected slide down in the order 
         */
        public static final int move_down=0x7f080029;
        /**  Menu item in slideshow edit screen for moving the selected slide up in the order 
         */
        public static final int move_up=0x7f080028;
        /**  "Type" value in "Message details" dialog 
         */
        public static final int multimedia_message=0x7f0800a4;
        /**  "Type" value in "Message details" dialog 
         */
        public static final int multimedia_notification=0x7f0800a5;
        /**  Titlebar string when there are more than one recipients 
         */
        public static final int multiple_recipients=0x7f08005f;
        /**  Formatting for prepending MMS message text with sender's name. 
         */
        public static final int name_colon=0x7f080021;
        /**  Command name to open a Compose screen; displays in conversation list 
         */
        public static final int new_message=0x7f080000;
        public static final int next=0x7f08016e;
        /**  Text to be used for negative response button in dialog boxes 
         */
        public static final int no=0x7f080071;
        public static final int no_number_for_contact=0x7f08013d;
        public static final int no_parandroid_description=0x7f08015d;
        public static final int no_public_keys=0x7f080146;
        public static final int no_recipient=0x7f080123;
        /**  Download Manager 
 When an error occurs downloading a new message and a subject isn't available, substitute
         this default subject. 
         */
        public static final int no_subject=0x7f0800e3;
        /**  Subject to display in the conversation list if there is no subject 
         */
        public static final int no_subject_view=0x7f080010;
        /**  Failed to send/download Notification dialog title. 
         */
        public static final int notification_failed_multiple=0x7f0800d5;
        /**  Failed to send/download Notification dialog title. 
         */
        public static final int notification_failed_multiple_title=0x7f0800d6;
        /**  Delivery Report Notification dialog title. 
         */
        public static final int notification_multiple=0x7f0800d3;
        /**  Delivery Report Notification dialog title. 
         */
        public static final int notification_multiple_title=0x7f0800d4;
        public static final int notify_tap_to_remove=0x7f080124;
        /**  Hint text in message body field when keyboard is hidden 
         */
        public static final int open_keyboard_to_compose_message=0x7f080042;
        public static final int parandroid_about=0x7f080112;
        public static final int parandroid_authenticate=0x7f080151;
        public static final int parandroid_authenticate_title=0x7f080152;
        public static final int parandroid_developers=0x7f080113;
        public static final int parandroid_public_key_snippet=0x7f080111;
        public static final int parandroid_send_public_key=0x7f080114;
        public static final int parandroid_set_password=0x7f080153;
        public static final int parandroid_set_password_title=0x7f080154;
        public static final int parandroid_snippet=0x7f080110;
        public static final int parandroid_specify_recipients=0x7f080155;
        public static final int password_not_changed=0x7f080150;
        public static final int passwords_dont_match=0x7f080127;
        public static final int passwords_too_short=0x7f080128;
        /**  Title of the number picker activity. 
         */
        public static final int pick_numbers_activity=0x7f0800ff;
        /**  Button text used for playing an attachment or slideshow (imperative verb) 
         */
        public static final int play=0x7f080073;
        /**  Settings item for setting the number of message to save for each conversation 
         */
        public static final int pref_messages_to_save=0x7f08008f;
        /**  Settings screen, section heading for MMS-specific settings 
         */
        public static final int pref_mms_settings_title=0x7f08007a;
        /**  Settings screen, section heading for notifications 
         */
        public static final int pref_notification_settings_title=0x7f080079;
        public static final int pref_parandroid=0x7f080156;
        /**  Settings screen, section heading for SMS-specific settings 
         */
        public static final int pref_sms_settings_title=0x7f08007b;
        /**  Settings screen, section heading for storage-specific settings 
         */
        public static final int pref_sms_storage_title=0x7f08007c;
        /**  Settings item description for boolean auto-delete messages setting 
         */
        public static final int pref_summary_auto_delete=0x7f080081;
        /**  Settings item description for integer auto-delete sms message limit 
         */
        public static final int pref_summary_delete_limit=0x7f080082;
        /**  Settings item description for entering SIM card message screen 
         */
        public static final int pref_summary_manage_sim_messages=0x7f08007d;
        /**  Settings item description for boolean MMS auto-retrieve option 
         */
        public static final int pref_summary_mms_auto_retrieval=0x7f080091;
        /**  Settings item description for boolean MMS delivery report setting 
         */
        public static final int pref_summary_mms_delivery_reports=0x7f08007e;
        /**  Settings item description for boolean MMS read report setting 
         */
        public static final int pref_summary_mms_read_reports=0x7f08007f;
        /**  Settings item description for boolean MMS auto-retrieve while roaming option 
         */
        public static final int pref_summary_mms_retrieval_during_roaming=0x7f080093;
        /**  Settings item description for boolean message notification option 
         */
        public static final int pref_summary_notification_enabled=0x7f08008b;
        /**  Settings item description for boolean vibrate option 
         */
        public static final int pref_summary_notification_vibrate=0x7f08008d;
        /**  Settings item description for boolean SMS delivery report setting 
         */
        public static final int pref_summary_sms_delivery_reports=0x7f080080;
        /**  Settings item for boolean option to enable/disable auto-deletion of messages 
         */
        public static final int pref_title_auto_delete=0x7f080087;
        /**  Settings item for entering SIM card message screen 
         */
        public static final int pref_title_manage_sim_messages=0x7f080083;
        /**  Settings item for boolean option to auto-retrieve incoming MMS messages 
         */
        public static final int pref_title_mms_auto_retrieval=0x7f080090;
        /**  Settings item for integer option to set MMS delete limit 
         */
        public static final int pref_title_mms_delete=0x7f080089;
        /**  Settings item for boolean option to enable/disable MMS delivery reports 
         */
        public static final int pref_title_mms_delivery_reports=0x7f080084;
        /**  Settings item for boolean option to enable/disable MMS read reports 
         */
        public static final int pref_title_mms_read_reports=0x7f080085;
        /**  Settings item for boolean option to auto-retrieve incoming MMS messages while roaming 
         */
        public static final int pref_title_mms_retrieval_during_roaming=0x7f080092;
        /**  Settings item for boolean option to display message notifications 
         */
        public static final int pref_title_notification_enabled=0x7f08008a;
        /**  Settings item for entering ringtone selection screen 
         */
        public static final int pref_title_notification_ringtone=0x7f08008e;
        /**  Settings item for boolean option to vibrate during message notification 
         */
        public static final int pref_title_notification_vibrate=0x7f08008c;
        /**  Settings item for integer option to set SMS delete limit 
         */
        public static final int pref_title_sms_delete=0x7f080088;
        /**  Settings item for boolean option to enable/disable SMS delivery reports 
         */
        public static final int pref_title_sms_delivery_reports=0x7f080086;
        /**  Title of Settings screen 
         */
        public static final int preferences_title=0x7f080077;
        /**  Button in the slide editor screen used to preview the slide (imperative verb) 
         */
        public static final int preview=0x7f080061;
        /**  Menu item in the slide editor screen used to preview the entire slideshow (imperative verb) 
         */
        public static final int preview_slideshow=0x7f080062;
        public static final int previous=0x7f08016f;
        /**  "Priority" value in "Message details" dialog 
         */
        public static final int priority_high=0x7f0800af;
        /**  Label in "Message details" dialog 
         */
        public static final int priority_label=0x7f0800ae;
        /**  "Priority" value in "Message details" dialog 
         */
        public static final int priority_low=0x7f0800b1;
        /**  "Priority" value in "Message details" dialog 
         */
        public static final int priority_normal=0x7f0800b0;
        public static final int protocol_too_high=0x7f080142;
        public static final int public_key=0x7f080132;
        public static final int public_keys_pending=0x7f080145;
        public static final int public_keys_saved=0x7f080144;
        /**  This is the confirm rate limit alert dialog title. 
         */
        public static final int rate_limit_surpassed=0x7f0800e7;
        public static final int received_encrypted_message=0x7f080141;
        /**  Label in "Message details" dialog 
         */
        public static final int received_label=0x7f0800aa;
        public static final int received_public_key=0x7f080140;
        /**  Label in "Report" window 
         */
        public static final int recipient_label=0x7f0800c7;
        public static final int reencrypting_messages=0x7f08013a;
        /**  Message that appears on screen while SIM card messages are retrieved 
         */
        public static final int refreshing=0x7f08000c;
        /**  Button next to an attachment during message composition to remove the attachment (imperative verb) 
         */
        public static final int remove=0x7f08003e;
        /**  Menu item in slide edit screen for removing the music from the slide being edited 
         */
        public static final int remove_music=0x7f080033;
        /**  Menu item in slide edit screen for removing the picture from the slide being edited 
         */
        public static final int remove_picture=0x7f080031;
        /**  Menu item in slideshow edit screen for removing the selected slide from the slideshow 
         */
        public static final int remove_slide=0x7f08002a;
        /**  Menu item in slide edit screen for removing the text from the slide being edited 
         */
        public static final int remove_text=0x7f08002f;
        /**  Menu item in slide edit screen for removing the video from the slide being edited 
         */
        public static final int remove_video=0x7f080035;
        /**  Button next to an attachment during message composition to replace the attachment (imperative verb) 
         */
        public static final int replace=0x7f08003d;
        /**  Button in the slide editor screen used to replace the attached picture 
         */
        public static final int replace_image=0x7f080063;
        /**  Button for resizing an image used in "image too large" dialog box (imperative verb) 
         */
        public static final int resize=0x7f080075;
        /**  Error message indicating that an image being attached is still too large to send even after resize 
         */
        public static final int resize_image_error_information=0x7f08004c;
        /**  Settings screen menu item for restoring all settings to default 
         */
        public static final int restore_default=0x7f080078;
        /**  Dialog text displayed when trying to resend an unsent message. 
         */
        public static final int retrying_dialog_body=0x7f0800b7;
        /**  Dialog text for display mode save dialog. 
         */
        public static final int save=0x7f080108;
        /**  Menu title to save a sound as a ringtone 
         */
        public static final int save_ringtone=0x7f0800f1;
        /**  Label in "Message details" dialog 
         */
        public static final int saved_label=0x7f0800ab;
        /**  Toast message on successful copying ringtone to drm provider 
         */
        public static final int saved_ringtone=0x7f0800f2;
        /**  Toast message on failed copying ringtone to drm provider 
         */
        public static final int saved_ringtone_fail=0x7f0800f3;
        /**  Search activity name 
         */
        public static final int search=0x7f080106;
        /**   Search empty results 
         */
        public static final int search_empty=0x7f080107;
        /**  Search hint 
         */
        public static final int search_hint=0x7f080105;
        /**  Application name shown when searching 
         */
        public static final int search_label=0x7f080104;
        /**  In duration selection dialog box, short version of "seconds" 
         */
        public static final int secs=0x7f08006c;
        /**  Title for audio file picker 
         */
        public static final int select_audio=0x7f0800ed;
        /**  Layout Selector Adapter. Slideshow layout dialog option for aligning an icon. 
         */
        public static final int select_bottom_text=0x7f0800d0;
        /**  Title of the select-contact-method activity. 
         */
        public static final int select_contact_method_activity=0x7f080103;
        /**  Message prompting the user to select a different item; item string as type-appropriate (e.g. "picture") 
         */
        public static final int select_different_media=0x7f080047;
        /**  Title of the layout-selector activity. 
         */
        public static final int select_layout_activity=0x7f0800fa;
        /**  This is the dialog title for the "Select link" dialog, shown when the user clicks on a
    chat in the chat history view if there are links in the chat message. The dialog displays the
    links if there are any 
         */
        public static final int select_link_title=0x7f0800f5;
        /**  Layout Selector Adapter. Slideshow layout dialog option for aligning an icon. 
         */
        public static final int select_top_text=0x7f0800d1;
        /**  Button in conversation screen for sending the message currently being composed (imperative verb) 
         */
        public static final int send=0x7f08003f;
        public static final int send_back_public_key_dialog=0x7f08013c;
        public static final int send_encrypted_message_failure=0x7f080131;
        public static final int send_encrypted_message_success=0x7f080130;
        public static final int send_encrypted_to=0x7f08012a;
        public static final int send_plain_to=0x7f08012b;
        public static final int send_public_key_dialog=0x7f08013b;
        public static final int send_public_key_failure=0x7f08012f;
        public static final int send_public_key_success=0x7f08012d;
        /**  Title of the send-using-MMS activity. 
         */
        public static final int send_using_mms_activity=0x7f080102;
        /**  Label in "Message details" dialog 
         */
        public static final int sent_label=0x7f0800a9;
        /**  Time and date a message was sent 
         */
        public static final int sent_on=0x7f080017;
        /**  Text to be used for affirmative response button in setting SMS limits dialog box 
         */
        public static final int set=0x7f080072;
        public static final int show_confirm_dialog=0x7f08015b;
        public static final int show_confirm_dialog_title=0x7f08015c;
        /**  Manage SIM Messages 
 Menu title to copy a selected message from the SIM card to the phone. 
         */
        public static final int sim_copy_to_phone_memory=0x7f0800ba;
        /**  Menu title to delete a selected messaged from the SIM card. 
         */
        public static final int sim_delete=0x7f0800bb;
        /**  Message that appears on the "SMS messges on SIM card" screen when there are no messages on the SIM card 
         */
        public static final int sim_empty=0x7f0800be;
        /**  Sim Full Notification dialog text. 
         */
        public static final int sim_full_body=0x7f0800d8;
        /**  Sim Full Notification dialog title. 
         */
        public static final int sim_full_title=0x7f0800d7;
        /**  Title of screen displaying messages on SIM card 
         */
        public static final int sim_manage_messages_title=0x7f0800bc;
        /**  Context menu item but currently commented out in 1.0. 
         */
        public static final int sim_view=0x7f0800bd;
        public static final int skip=0x7f080170;
        /**  Name of the Nth slide, shown in the list in the slideshow editor. 
         */
        public static final int slide_number=0x7f0800f6;
        /**  Header of slideshow showing which slide is being displayed 
         */
        public static final int slide_show_part=0x7f08002e;
        /**  Title of the slideshow activity. 
         */
        public static final int slideshow_activity=0x7f080100;
        /**  Device Full Notification dialog text. 
         */
        public static final int sms_full_body=0x7f0800da;
        /**  Device Full Notification dialog title. 
         */
        public static final int sms_full_title=0x7f0800d9;
        /**  Sms's Being Rejected Notification dialog text. 
         */
        public static final int sms_rejected_body=0x7f0800dc;
        /**  Sms's Being Rejected Notification dialog title. 
         */
        public static final int sms_rejected_title=0x7f0800db;
        public static final int specify_recipients=0x7f08011c;
        public static final int specify_recipients_none_checked=0x7f08012c;
        /**  Status in "Report" window 
         */
        public static final int status_failed=0x7f0800c4;
        /**  Label in "Report" window 
         */
        public static final int status_label=0x7f0800c8;
        /**  Delivery Report Activity 
 Status in "Report" window 
         */
        public static final int status_none=0x7f0800c0;
        /**  Status in "Report" window 
         */
        public static final int status_pending=0x7f0800c1;
        /**  Status in "Report" window 
         */
        public static final int status_read=0x7f0800c2;
        /**  Status in "Report" window 
         */
        public static final int status_received=0x7f0800c3;
        /**  Status in "Report" window 
         */
        public static final int status_rejected=0x7f0800c6;
        /**  Status in "Report" window 
         */
        public static final int status_unread=0x7f0800c5;
        /**  Title of the activity that tells the user about storage limits. 
         */
        public static final int storage_limits_activity=0x7f0800f8;
        /**  Dialog message for dialog that informs user about new storage settings. 
         */
        public static final int storage_limits_message=0x7f08010a;
        /**  Button title for dialog that informs user about new storage settings. 
         */
        public static final int storage_limits_setting=0x7f08010b;
        /**  Button title to dismiss dialog that informs user about new storage settings. 
         */
        public static final int storage_limits_setting_dismiss=0x7f08010c;
        /**  Dialog title for dialog that informs user about new storage settings. 
         */
        public static final int storage_limits_title=0x7f080109;
        /**  Hint displayed in subject edit text box when adding a subject 
         */
        public static final int subject_hint=0x7f080038;
        /**  Label in "Message details" dialog 
         */
        public static final int subject_label=0x7f0800ac;
        public static final int successfully_changed_password=0x7f08014f;
        public static final int tap_to_accept=0x7f080133;
        /**  "Type" value in "Message details" dialog 
         */
        public static final int text_message=0x7f0800a3;
        /**  Label in "Message details" dialog 
         */
        public static final int to_address_label=0x7f0800a7;
        /**  Hint displayed in message recipient text box when starting a new conversation 
         */
        public static final int to_hint=0x7f080037;
        /**  Label prepended to recipient's name in Undelivered Messages screen 
         */
        public static final int to_label=0x7f080094;
        /**  Brief message that appears when too many recipients have been added 
         */
        public static final int too_many_recipients=0x7f08005e;
        /**  Toast message when a user tries to send a Mms message when there are already too many
         outstanding unsent message. 
         */
        public static final int too_many_unsent_mms=0x7f08010d;
        /**  Button used for trying to send a message that has some valid recipients and some
         invalid recipients, in spite of the warning presented to the user 
         */
        public static final int try_to_send=0x7f080076;
        /**  Multimedia type used in building other messages.
         For instance: Sorry, you cannot add this audio to your message. 
         */
        public static final int type_audio=0x7f0800dd;
        /**  Multimedia type used in building other messages.
         For instance: Sorry, you cannot add this picture to your message. 
         */
        public static final int type_picture=0x7f0800de;
        /**  Hint text in message body field when keyboard is exposed 
         */
        public static final int type_to_compose_text_enter_to_send=0x7f080041;
        /**  Hint in slide text field before text is typed 
         */
        public static final int type_to_compose_text_or_leave_blank=0x7f080069;
        /**  Multimedia type used in building other messages.
         For instance: Sorry, you cannot add this video to your message. 
         */
        public static final int type_video=0x7f0800df;
        /**  Dialog box message indicating that a message could not be delivered, including the time of last attempt 
         */
        public static final int undelivered_msg_dialog_body=0x7f08001b;
        /**  Dialog box title brought up when warning the user that a message could not be delivered 
         */
        public static final int undelivered_msg_dialog_title=0x7f08001a;
        /**  Dialog box message indicating that a message could not be delivered 
         */
        public static final int undelivered_sms_dialog_body=0x7f08001c;
        /**  When an error occurs downloading a new message and the sender is unknown, substitute
         this default text. 
         */
        public static final int unknown_sender=0x7f0800e4;
        public static final int unsupported_contact=0x7f08013e;
        /**  Error message indicating the format for the specified media type (e.g. "picture") is unsupported 
         */
        public static final int unsupported_media_format=0x7f080046;
        /**  Button next to an attachment during message composition to view the attachment (imperative verb) 
         */
        public static final int view=0x7f08003c;
        /**  Context menu item on an individual message for viewing a delivery report 
         */
        public static final int view_delivery_report=0x7f080015;
        /**  Context menu item on an individual message for viewing message details such as time and date 
         */
        public static final int view_message_details=0x7f080014;
        /**  Context menu item on an individual message for viewing an attached picture 
         */
        public static final int view_picture=0x7f080012;
        /**  Context menu item on an individual message for viewing an attached slideshow 
         */
        public static final int view_slideshow=0x7f080013;
        public static final int wrong_password=0x7f080129;
        /**  Text to be used for affirmative response button in dialog boxes 
         */
        public static final int yes=0x7f080070;
    }
    public static final class style {
        public static final int TextAppearance=0x7f0a0000;
        public static final int TextAppearance_SearchResult=0x7f0a0001;
        public static final int TextAppearance_SearchResult_Subtitle=0x7f0a0003;
        public static final int TextAppearance_SearchResult_Title=0x7f0a0002;
    }
    public static final class xml {
        public static final int mms_config=0x7f050000;
        public static final int preferences=0x7f050001;
        public static final int searchable=0x7f050002;
    }
}
